Django/askdjango/askdjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView

#def root(request):
#    return redirect('blog:post_list')

urlpatterns = [
    #url(r'^$',root,name='root'),
    url(r'^$',lambda r: redirect('blog:post_list'),name='root'),
    #url(r'^$',RedirectView.as_view(pattern_name='blog:post_list')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/',include('accounts.urls')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls',namespace='dojo')),
] ## 최상위 URL 패턴


if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/',include(debug_toolbar.urls))
    ]

Django/askdjango/blog/urls.py
#blog/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^$', views.post_list, name='post_list'), #시작과 끝이라는 뜻(최상위 주소) # 함수 자체를 넘겨준 것 //빈문자열을 뜻함
    #url(r'^(?P<id>\d+)/$') <id> 변수고.. 그 변수가 \d+ <--[0-9] 사이라면?
    # 패턴이 없다면.. localhost:8000/blog/
    url(r'^(?P<id>\d+)/$', views.post_detail,name='post_detail'),


]

## urls 요청이 들어올 때마다 처음부터 끝까지 순차적으로 url 패턴 검사 한다.

Django/askdjango/blog/models.py
#blog/models.py
import re
from django.db import models
from django.forms import ValidationError
from django.conf import settings


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')


class Post(models.Model):
#    title = models.CharField(max_length=100,
#    choices=(
#        ('제목1','제목 1레이블'), #('저장될 값','UI에 보여질 레이블')
#        ('제목2','제목 2레이블'),
#        ('제목3','제목 3레이블'),
#    ))#길이 제한이 있는 문자열
    STATUS_CHOICES = (
        ('d','Draft'),
        ('p','Published'),
        ('w','Withdrawn'),
    )
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, help_text='제목 입력..100내')#, verbose_name='제목')
    content = models.TextField() # 길이 제한이 없는 문자열
    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=100, blank=True,validators=[lnglat_validator],help_text='경도/위도 포맷으로 입력')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag',blank=True) #문자열로??
    created_at = models.DateTimeField(auto_now_add=True) #최초 저장될 때 시간
    update_at = models.DateTimeField(auto_now=True) # 해당 레코드가 갱신이 될때 마다 일시 저장
# Create your models here.
    class Meta:
        ordering = ['-id']

    def __str__(self):
        return self.title

"""
makemigrations: 마에그레이션 파일 생성
migrate: 실제 마이그레이션 진행
이미 진행된 Migrate 파일은 지우지 않는다.!!!
"""

#1:N 의 관계 모델링
class Comment(models.Model):
    post = models.ForeignKey(Post) # 클래스지정?
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return self.name

Django/askdjango/blog/views.py
#blog/views.py
from django.http import Http404
from django.shortcuts import get_object_or_404,render
from .models import Post

# Create your views here.

def post_list(request):
    qs = Post.objects.all()
    
    q = request.GET.get('q','')
    if q:
        qs = qs.filter(title__icontains=q)
    

    return render(request, 'blog/post_list.html',{
        'post_list':qs,
        'q':q,
        }) #view 에서 template 지정하는 형식

# blog/templates/blog/post_list.html


def post_detail(request,id):
    #try:
    #    post = Post.objects.get(id=id)
    #except Post.DoesNotExist:
    #    raise Http404

    post=get_object_or_404(Post,id=id)

    return render(request,'blog/post_detail.html',{
        'post':post,
    })

Django/askdjango/blog/templates/blog/layout.html
{%extends "layout.html" %} <!--\askdjango\templates\layout.html-->

{% block title %} AskDjango's Blog {% endblock %}


{#https://docs.djangoproject.com/ko/2.1/ref/templates/#}

Django/askdjango/blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %} 
{% block title %} 
    {{post.title}} 
{% endblock title %} 
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-sm-12">
            <h2>{{post.title}}</h2>
            {{post.content|linebreaks}}
            <hr/>
            <h3>Comments</h3>
            <ul>
                {% for comment in post.comment_set.all %}
                <li></li>
                {{comment.message}}
                <small>by {{comment.author}}</small>
                <small>at {{comment.updated_at}}</small>
                </li>
                {% endfor %}
            </ul>
            <hr>
            <a href="{% url "blog:post_list" %}" class="btn btn-primary">글 목록</a>
        </div>
    </div>
</div>
{% endblock content %}

Django/askdjango/blog/templates/blog/post_list.html
{% extends "blog/layout.html" %} {% block content %}
<div class="container">
    <div class="jumbotron">
        <h1>Django Template <sup>by AskDjango</sup></h1>
        <p>여러분의 파이썬/장고 페이스메이커가 되어드리겠습니다.</p>
        <p>
            <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                AskDjango 페이스북 그룹 &raquo;
            </a>
        </p>
    </div>
    <div class=row>
        <div class="col-sm-12">
            <div class="alert alert-info">
                <ul>
                    <li>http://localhost:8000/blog/ 주소로 접속해보세요.</li>
                    <li>템플릿 경로를 blog/templates/post_list.html 경로가 아닌 blog/ templates/blog/post_list.html 경로를 쓰는 지에 대한 이유는, 후에 Template
                        Loader에서 설명합니다.
                    </li>
                </ul>
            </div>
            <p>
                <form action="" method="GET">
                    <input type="text" name="q" value="{{q}}" />
                    <input type="submit" value="검색" class="btn btn-primary" />
                </form>
            </p>
            <table class="table table-horver table-bordered">
                <tbody>
                    <tr>
                        <th>id</th>
                        <th>title</th>
                        <th>created_at</th>
                        <th>update_at</th>
                    </tr>
                    {% for post in post_list %}
                    <tr>
                        <td>{{post.id}}</td>
                        <td><a href="{% url "blog:post_detail" post.id %}">{{post.title}}</a></td>

                        <!--<a href="/blog/{{post.id}}/">
                                            {{post.title}}
                                            </a>-->
                        <td><small>by {{post.update_at}}</small></td>
                        <td>><small>at {{post.created_at}}</small></td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

<!--
In [2]: from django.core.urlresolvers import reverse
In [7]: reverse('blog:post_list')
Out[7]: '/blog/'

In [8]: reverse('blog:post_detail',args=[10])
Out[8]: '/blog/10/'

In [11]: reverse('blog:post_detail',kwargs={'id':2})
Out[11]: '/blog/2/'

In [12]: from django.shortcuts import resolve_url

In [13]: resolve_url('blog:post_list')
Out[13]: '/blog/'

In [14]: resolve_url('blog:post_detail',10)
Out[14]: '/blog/10/'

In [15]: resolve_url('blog:post_detail',id=10)
Out[15]: '/blog/10/'

In [16]: from django.shortcuts import redirect

In [17]: redirect('blog:post_detail',10)
Out[17]: <HttpResponseRedirect status_code=302, "text/html; charset=utf-8", url="/blog/10/">

-->